import { NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { getAdminAuth, getAdminDb } from "../../../../lib/firebase-admin";
import { ensureUserId } from "../../../../lib/server/user-id";
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
const plain = (snapshot) => ({ id: snapshot.id, ...snapshot.data() });
function failed(stage, error) { console.error("[teacher-assignment-api] failed", { stage, code: error?.code || "unknown" }); return NextResponse.json({ message: "Unable to manage teacher assignments. Check the server log for the safe error code." }, { status: 500 }); }
async function requireManager(request) { const token = request.headers.get("authorization")?.replace(/^Bearer\s+/i, ""); if (!token) return { denied: NextResponse.json({ message: "Administrator access is required." }, { status: 401 }) }; const auth = getAdminAuth(), db = getAdminDb(), decoded = await auth.verifyIdToken(token), profile = await db.collection("users").doc(decoded.uid).get(); if (!profile.exists || profile.data().active === false || !["Admin", "Director"].includes(profile.data().role)) return { denied: NextResponse.json({ message: "Administrator access is required." }, { status: 403 }) }; return { db }; }
export async function GET(request) { try { const access = await requireManager(request); if (access.denied) return access.denied; const [teacherDocs, courseDocs, classDocs] = await Promise.all([access.db.collection("users").where("role", "==", "Teacher").get(), access.db.collection("courses").get(), access.db.collection("classes").get()]); const teachers = teacherDocs.docs.map(plain).map(({ id, displayName, email, phone, photoURL, userId, department, designation, active }) => ({ id, displayName: displayName || "", email: email || "", phone: phone || "", photoURL: photoURL || "", userId: userId || null, department: department || "", designation: designation || "", active: active !== false })).filter((teacher) => teacher.active); await Promise.all(teachers.filter((teacher) => !teacher.userId).map((teacher) => ensureUserId(access.db, teacher.id).then((userId) => { teacher.userId = userId; }))); return NextResponse.json({ teachers, courses: courseDocs.docs.map(plain).map((course) => ({ id: course.id, title: course.title || course.name || "Untitled course", teacherIds: course.teacherIds || [] })), classes: classDocs.docs.map(plain).map((item) => ({ id: item.id, name: item.name || item.title || "Untitled class", courseId: item.courseId || "", teacherIds: item.teacherIds || [] })) }); } catch (error) { return failed("directory load", error); } }
export async function PATCH(request) { try { const access = await requireManager(request); if (access.denied) return access.denied; const { type, id, teacherIds } = await request.json(); if (![["course", "courses"], ["class", "classes"]].some(([kind]) => kind === type) || !id || !Array.isArray(teacherIds) || teacherIds.some((value) => typeof value !== "string")) return NextResponse.json({ message: "Invalid assignment request." }, { status: 400 }); const collection = type === "course" ? "courses" : "classes", ref = access.db.collection(collection).doc(id), [target, teacherDocs] = await Promise.all([ref.get(), access.db.getAll(...teacherIds.map((teacherId) => access.db.collection("users").doc(teacherId)))]); if (!target.exists) return NextResponse.json({ message: `${type === "course" ? "Course" : "Class"} not found.` }, { status: 404 }); if (teacherDocs.some((teacher) => !teacher.exists || teacher.data().role !== "Teacher" || teacher.data().active === false)) return NextResponse.json({ message: "Choose only active teacher accounts." }, { status: 400 }); await ref.update({ teacherIds: [...new Set(teacherIds)], updatedAt: FieldValue.serverTimestamp() }); return NextResponse.json({ ok: true }); } catch (error) { return failed("assignment save", error); } }

