"use client";
import { useEffect, useState } from "react";
import { createStudent, loadStudentDirectory, updateStudent } from "../lib/services/student-service";
import StudentTable from "./students/StudentTable";
import StudentForm from "./students/StudentForm";
import StudentDetails from "./students/StudentDetails";
const blank = { displayName: "", email: "", phone: "", courseId: "", password: "", confirmPassword: "" };
function Dialog({ title, children, onClose }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><button onClick={onClose} className="text-xl text-slate-500">×</button></div>{children}</div></div>; }
export default function StudentManagement({ role }) {
 const [students,setStudents]=useState([]),[courses,setCourses]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[form,setForm]=useState(blank),[creating,setCreating]=useState(false),[editing,setEditing]=useState(null),[viewing,setViewing]=useState(null),[saving,setSaving]=useState(false);
 async function load() { setLoading(true); try { const data=await loadStudentDirectory(); setStudents(data.students); setCourses(data.courses); setError(""); } catch (e) { setStudents([]); setCourses([]); setError(e.message || "Unable to load students."); } finally { setLoading(false); } }
 useEffect(() => { void Promise.resolve().then(load); }, []);
 const close=()=>{setCreating(false);setEditing(null);setViewing(null);setForm(blank);};
 async function submit(event) { event.preventDefault(); if (!editing && form.password !== form.confirmPassword) return setError("Passwords do not match."); setSaving(true); try { if (editing) await updateStudent({uid:editing.id,displayName:form.displayName,phone:form.phone,active:form.active}); else await createStudent(form); close();setNotice(editing ? "Student profile updated." : "Student account and enrollment created.");await load(); } catch(e) {setError(e.message || "Unable to save student.");} finally {setSaving(false);} }
 async function deactivate(student) { if (!window.confirm(`Deactivate ${student.displayName || student.email}? They will no longer be able to sign in.`)) return; try {await updateStudent({uid:student.id,active:false});setNotice("Student deactivated safely.");await load();}catch(e){setError(e.message || "Unable to deactivate student.");} }
 return <div className="space-y-6"><section className="flex flex-wrap items-center justify-between gap-4 rounded-3xl bg-gradient-to-r from-slate-900 to-red-950 p-6 text-white shadow-xl"><div><p className="text-[10px] font-bold uppercase tracking-widest text-red-300">{role} workspace</p><h2 className="mt-2 text-3xl font-black">Students Directory</h2><p className="mt-2 text-sm text-slate-300">Manage, add, and inspect real student records.</p></div><button onClick={()=>{setError("");setCreating(true);}} className="rounded-xl bg-red-600 px-4 py-3 text-xs font-bold">Add New Record</button></section>{notice&&<p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{notice}</p>}{error&&<div className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700"><b>Unable to load students.</b><p>{error}</p></div>}{loading?<p className="py-10 text-center text-sm text-slate-500">Loading students...</p>:error?null:<StudentTable students={students} search={search} onSearch={setSearch} onView={setViewing} onEdit={(student)=>{setEditing(student);setForm({displayName:student.displayName||"",phone:student.phone||"",active:student.active!==false});}} onDeactivate={deactivate}/>} {creating&&<Dialog title="Add student" onClose={close}><StudentForm form={form} setForm={setForm} courses={courses} saving={saving} onSubmit={submit}/></Dialog>}{editing&&<Dialog title="Edit student" onClose={close}><StudentForm form={form} setForm={setForm} courses={courses} editing={editing} saving={saving} onSubmit={submit}/></Dialog>}{viewing&&<Dialog title="Student details" onClose={close}><StudentDetails student={viewing}/></Dialog>}</div>;
}

